//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoVerhuurKantoor_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency_Car
    {
        public int agency_car_id { get; set; }
        public int agency_id { get; set; }
        public int car_id { get; set; }
        public int rental_id { get; set; }
        public int pricePerNight { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Car Car { get; set; }
        public virtual Rental Rental { get; set; }
    }
}
