//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoVerhuurKantoor_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int rental_id { get; set; }
        public int customer_id { get; set; }
        public int agency_car_id { get; set; }
        public Nullable<System.DateTime> startDdate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    
        public virtual Agency_Car Agency_Car { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
